#!/bin/bash

export DOCKER_TAG="speedtest-cli"

export DOCKER_PLATFORMS="linux/386,linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v6,linux/arm/v5,linux/mips64le,linux/ppc64le,linux/riscv64,linux/s390x"

export ARTIFACTS_FOLDER="artifacts"

export TARGET_SPT_NAME="speedtest-c"
export TARGET_TAR_NAME="tar"
export TARGET_GZP_NAME="gzip"
export CA_CERTS_NAME="ca-certs.tgz"

# Styles
export END="\e[0m"
export BLD="\e[1m"
export DEM="\e[2m"
export ITL="\e[3m"
export UND="\e[4m"
export BLN="\e[5m"
export INV="\e[7m"
export HID="\e[8m"
export CRS="\e[9m"
# Colors
export BLK="\e[30m"
export RED="\e[31m"
export GRN="\e[32m"
export YEL="\e[33m"
export BLU="\e[34m"
export MNG="\e[35m"
export CYN="\e[36m"
export GRY="\e[37m"
export DEF="\e[39m"
export DGR="\e[90m"
export LRE="\e[91m"
export LGR="\e[92m"
export LYE="\e[93m"
export LBL="\e[94m"
export LMG="\e[95m"
export LCY="\e[96m"
export WIT="\e[97m"

#-----------------------------------------------------------#
# Go to the script's directory
pushd "$(dirname "$(readlink -f "$BASH_SOURCE")")" >/dev/null

# Call main
bash scripts/main.sh $@

# Return to the previous directory
popd >/dev/null
